//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace curdviewmodel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Studentdetail
    {
        public static object ViewModel { get; internal set; }
        public int ?ID { get; set; }
        public String Sid { get; set; }
        public string Sname { get; set; }
        public string Age { get; set; }
        public string Adress { get; set; }
        public string classes { get; set; }
        public string Fname { get; set; }
        public string Phno { get; set; }
        public string Gmail { get; set; }
        public string Pincode { get; set; }
    }
}
